version: '3.8'

services:
  php:
    build: .
    container_name: php_container
    ports:
      - "8000:80"  # Expose container's port 80 to host's port 8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:

